### ISSUE TITLE
Suggestion: Valoration/Confirmation for each Pokemon

### ISSUE THREAD

**Issue by caito103** [felipefrancisco/pokemon-go-map#5] opened 2016-07-14 21:17 UTC
As a suggestion, maybe you can put for each Pokemon in the map a Ranking style mod, so the people can select if the information of a specific Pokemon is true or not, and if a pokemon have a determinated number of votes that the information is false, remove it from the map. If you need help programming or something, do not hesitate to contact me. :)

**Comment by felipefrancisco** [comment] 2016-07-16 13:33
Thanks! Will work on a ranking/reporting system asap.

Thanks for all support!

**Comment by felipefrancisco** [comment] 2016-07-16 13:58
Duplicate of https://github.com/felipefrancisco/pokemon-go-map/issues/4

**Closed as completed** 2016-07-16 13:58 UTC
Labels: duplicate, enhancement
