### ISSUE TITLE
Map lagging

### ISSUE THREAD

**Issue by pablohpsilva** [felipefrancisco/pokemon-go-map#3] opened 2016-07-14 16:46 UTC
The map is taking too long to start working. Maybe if you set asynchronous calls it would work faster.

1- Open the link
2- wait about 14s so I can move around and see things

**Comment by felipefrancisco** [comment] 2016-07-14 19:01
Thanks for the report.

The delay is being caused by the maps api. Its taking some time to place and load 1000+ images on the map. I'm working on it right now, hope this will be solved by the morning.

**Comment by felipefrancisco** [comment] 2016-07-16 13:32
@pablohenrique Map lagging is 70% solved, give it a try now :)

**Comment by felipefrancisco** [comment] 2016-07-16 13:56
Closing this issue since the map lagging is mostly solved, I'll focus on other stuff and come back to the lagging by the end of the weekend. Thanks for the support!

**Closed as completed by felipefrancisco** 2016-07-16 13:56 UTC
Labels: bug
